app = 'zen-demo-ruby-danger'
primary_region = 'ams'
console_command = '/rails/bin/rails console'

[build]

[env]
  AIKIDO_DISABLE = 'true'

[processes]
  app = './bin/rails server'

[[vm]]
  memory = '2048mb'
  cpu_kind = 'performance'
  cpus = 1
